security.protocol=SSL
ssl.truststore.location=/app/clients-creds/kafka_user.truststore.jks
ssl.truststore.password=changeit
ssl.keystore.location=/app/clients-creds/kafka_user.keystore.jks
ssl.keystore.password=changeit
ssl.endpoint.identification.algorithm=
client.id=producer-client
